window.blogsData = window.blogsData || [];
(function() {
    let blog = {
        "id": "speckofdust",
        "name": "speckofdust",
        "platform": "tistory",
        "blogUrl": "https://speckofdust.tistory.com",
        "categoryNo": "영어 관련 지식",
        "parentCategoryNo": "",
        "posts": []
    };
    blog.posts.push({"id": "post_270", "title": "'과소/과대 평가' 영어로 - under(over)estimate? under(over)rate?", "link": "https://speckofdust.tistory.com/270"});
    blog.posts.push({"id": "post_267", "title": "'연락을 하다, 유지하다, 끊기다...' 영어로 표현하기 ('touch' 이용)", "link": "https://speckofdust.tistory.com/267"});
    blog.posts.push({"id": "post_268", "title": "minimum과 minimal의 구별 (cf. '미니멀 라이프'라고 하는 이유)", "link": "https://speckofdust.tistory.com/268"});
    blog.posts.push({"id": "post_269", "title": "정확히 어떤 의미로 쓰이는 건지 헷갈리는 표현 - 'as of'", "link": "https://speckofdust.tistory.com/269"});
    blog.posts.push({"id": "post_266", "title": "영어로 나이를 표현할 때, '초반, 중반, 후반' - 어떻게 표현할까?", "link": "https://speckofdust.tistory.com/266"});
    blog.posts.push({"id": "post_263", "title": "요리기구 및 주방용품(밥솥, 국자, 주걱, 도마 등등.. ) - 영어로 표현하기", "link": "https://speckofdust.tistory.com/263"});
    blog.posts.push({"id": "post_265", "title": "'가리키다' 영어로 - 'point at'과 'point to'의 구별", "link": "https://speckofdust.tistory.com/265"});
    blog.posts.push({"id": "post_264", "title": "'직접' 영어로 - (by) oneself/on one's own, directly, in person 구별", "link": "https://speckofdust.tistory.com/264"});
    blog.posts.push({"id": "post_260", "title": "'기원전-BC(Before Chirst)', '기원후-AD(Anno Domini)' -각 표현에 관한 설명", "link": "https://speckofdust.tistory.com/260"});
    blog.posts.push({"id": "post_261", "title": "'부은' 영어로 - 'puffy'와 'swollen'의 구별", "link": "https://speckofdust.tistory.com/261"});
    blog.posts.push({"id": "post_262", "title": "프리마돈나 - pre madonna (x), prima donna (o)", "link": "https://speckofdust.tistory.com/262"});
    blog.posts.push({"id": "post_258", "title": "'계단'과 관련된 서로 다른 표현 - stair, staircase, stairway, stairwell - 구분하기", "link": "https://speckofdust.tistory.com/258"});
    blog.posts.push({"id": "post_256", "title": "'따라잡다, 밀린 일을 하다' 영어로 - catch up (+with, on, to)", "link": "https://speckofdust.tistory.com/256"});
    blog.posts.push({"id": "post_254", "title": "근육 이름 풀이 - '대퇴사두근 - quadriceps femoris', '대퇴이두근 - biceps femoris' (cf. 햄스트링 - hamstring)", "link": "https://speckofdust.tistory.com/254"});
    blog.posts.push({"id": "post_255", "title": "'~공포증(~phobia)' - acrophobia, claustrophobia, agoraphobia 등등..", "link": "https://speckofdust.tistory.com/255"});
    blog.posts.push({"id": "post_257", "title": "'걸어서' 영어로 - by foot? on foot?", "link": "https://speckofdust.tistory.com/257"});
    blog.posts.push({"id": "post_250", "title": "'평일에/주말에' - 영어로 표현하기", "link": "https://speckofdust.tistory.com/250"});
    blog.posts.push({"id": "post_251", "title": "근육 이름 풀이 - '복근 - abdominal muscle(s)' (cf. 복직근, 외복사근, 내복사근, 복횡근)", "link": "https://speckofdust.tistory.com/251"});
    blog.posts.push({"id": "post_252", "title": "근육 이름 풀이 - '둔근(엉덩이 근육) - gluteal muscle(s)' (cf. 대둔근, 중둔근, 소둔근)", "link": "https://speckofdust.tistory.com/252"});
    blog.posts.push({"id": "post_253", "title": "'병에 걸리다' - 영어로 표현하기", "link": "https://speckofdust.tistory.com/253"});
    blog.posts.push({"id": "post_246", "title": "근육 이름 풀이 - '상완이두근(biceps brachii)과 상완삼두근(triceps brachii)'", "link": "https://speckofdust.tistory.com/246"});
    blog.posts.push({"id": "post_248", "title": "근육 이름 풀이 - '승모근(등세모근) - Trapezius (muscle)'", "link": "https://speckofdust.tistory.com/248"});
    blog.posts.push({"id": "post_249", "title": "근육 이름 풀이 - '대흉근(큰가슴근) - Pectoralis major(=Pec) (cf. 소흉근)", "link": "https://speckofdust.tistory.com/249"});
    blog.posts.push({"id": "post_247", "title": "근육 이름 풀이 - '삼각근(어깨세모근) - deltoid (muscle)'", "link": "https://speckofdust.tistory.com/247"});
    blog.posts.push({"id": "post_245", "title": "근육 이름 풀이 - '광배근(=활배근, 넓은등근) - Latissimus dorsi(=Lat)'", "link": "https://speckofdust.tistory.com/245"});
    blog.posts.push({"id": "post_244", "title": "'sequence(=순서)'와 연관된 단어들에 대해 (cf. 시퀄, 프리퀄의 의미)", "link": "https://speckofdust.tistory.com/244"});
    blog.posts.push({"id": "post_242", "title": "'잠꼬대, 잠꼬대하다' - 영어로 표현하기", "link": "https://speckofdust.tistory.com/242"});
    blog.posts.push({"id": "post_243", "title": "'발생률, 발병률, 유병률, 치사율, 치명률' - 영어로 (+각각의 개념)", "link": "https://speckofdust.tistory.com/243"});
    blog.posts.push({"id": "post_240", "title": "돈을 쓰다, 돈을 내다, 돈이 들다 영어로 - spend, pay, cost", "link": "https://speckofdust.tistory.com/240"});
    blog.posts.push({"id": "post_241", "title": "'엄밀히 말하면' 영어로 - 'technically speaking'이라고 하는 이유", "link": "https://speckofdust.tistory.com/241"});
    blog.posts.push({"id": "post_238", "title": "'both, either, neither' - 제대로 이해하기", "link": "https://speckofdust.tistory.com/238"});
    blog.posts.push({"id": "post_239", "title": "'침엽수, 활엽수' / '상록수, 낙엽수' - 영어로 표현하기", "link": "https://speckofdust.tistory.com/239"});
    blog.posts.push({"id": "post_234", "title": "'a number of'와 'the number of' 구별 (심화)", "link": "https://speckofdust.tistory.com/234"});
    blog.posts.push({"id": "post_237", "title": "'사실상, 실질적으로' 영어로 - practically, virtually, effectively", "link": "https://speckofdust.tistory.com/237"});
    blog.posts.push({"id": "post_235", "title": "'각각' 영어로 - each? respectively?", "link": "https://speckofdust.tistory.com/235"});
    blog.posts.push({"id": "post_236", "title": "(차에) 태워주다, 내려주다 - 영어로 표현하기", "link": "https://speckofdust.tistory.com/236"});
    blog.posts.push({"id": "post_231", "title": "'해결하다' 영어로 - solve와 resolve의 구별", "link": "https://speckofdust.tistory.com/231"});
    blog.posts.push({"id": "post_232", "title": "'trade-off'의 의미는? (cf. give and take와 zero-sum)", "link": "https://speckofdust.tistory.com/232"});
    blog.posts.push({"id": "post_230", "title": "'녹다(녹이다)' 영어로 - melt, defrost, thaw의 구별", "link": "https://speckofdust.tistory.com/230"});
    blog.posts.push({"id": "post_233", "title": "'(~의) 편을 들다', '~의 편이다' - 영어로 표현하기", "link": "https://speckofdust.tistory.com/233"});
    blog.posts.push({"id": "post_227", "title": "'몽유병' 영어로 - somnambulism, noctambulism, sleepwalking", "link": "https://speckofdust.tistory.com/227"});
    blog.posts.push({"id": "post_226", "title": "유사한 세 단어 - classy, classic, classical의 구별", "link": "https://speckofdust.tistory.com/226"});
    blog.posts.push({"id": "post_228", "title": "'토끼' 영어로 - rabbit과 hare의 구별", "link": "https://speckofdust.tistory.com/228"});
    blog.posts.push({"id": "post_229", "title": "'거북이' 영어로 - turtle과 tortoise의 구별", "link": "https://speckofdust.tistory.com/229"});
    blog.posts.push({"id": "post_223", "title": "'눈'과 관련된 표현 中 '근시, 원시, 난시' - 영어로 표현하기", "link": "https://speckofdust.tistory.com/223"});
    blog.posts.push({"id": "post_224", "title": "'사시(눈)' - 영어로 표현하기", "link": "https://speckofdust.tistory.com/224"});
    blog.posts.push({"id": "post_222", "title": "'이식' 영어로 - implant와 transplant의 구별", "link": "https://speckofdust.tistory.com/222"});
    blog.posts.push({"id": "post_225", "title": "'격일로/격주로/격월로/격년으로' - 영어로 표현하기 (cf. '비엔날레'의 뜻)", "link": "https://speckofdust.tistory.com/225"});
    blog.posts.push({"id": "post_220", "title": "'차를 멈추다/세우다' 영어로 - pull over (그리고 그 유래)", "link": "https://speckofdust.tistory.com/220"});
    blog.posts.push({"id": "post_219", "title": "'마중하다'와 '배웅하다' - 영어로 표현하기", "link": "https://speckofdust.tistory.com/219"});
    blog.posts.push({"id": "post_218", "title": "회사 이름 뒤의 Inc, Corp, Ltd, plc 등등... 무엇의 줄임말일까", "link": "https://speckofdust.tistory.com/218"});
    blog.posts.push({"id": "post_221", "title": "'배꼽티' 영어로 - 크롭티? 크롭탑?", "link": "https://speckofdust.tistory.com/221"});
    blog.posts.push({"id": "post_215", "title": "피부의 여러 상태(촉촉한, 건조한, 주름진 등등...) - 영어로 표현하기", "link": "https://speckofdust.tistory.com/215"});
    blog.posts.push({"id": "post_214", "title": "'미루다(연기하다)'와 '앞당기다' - 영어로 표현하기", "link": "https://speckofdust.tistory.com/214"});
    blog.posts.push({"id": "post_216", "title": "세계의 지역을 4등분 한 영어 표현 - APAC, EMEA, LATAM(LAC), NORAM(NA, NAM)에 대해", "link": "https://speckofdust.tistory.com/216"});
    blog.posts.push({"id": "post_217", "title": "'조미료, 향신료, 감미료' - 영어로는?", "link": "https://speckofdust.tistory.com/217"});
    blog.posts.push({"id": "post_213", "title": "'복잡한' 영어로 - complex와 complicated의 차이?", "link": "https://speckofdust.tistory.com/213"});
    blog.posts.push({"id": "post_211", "title": "'혼잣말/혼잣말하다' - 영어로 표현하기", "link": "https://speckofdust.tistory.com/211"});
    blog.posts.push({"id": "post_212", "title": "'접종' 영어로 - vaccination, immunization, inoculation의 구별", "link": "https://speckofdust.tistory.com/212"});
    blog.posts.push({"id": "post_210", "title": "'이용하다/활용하다/써먹다' 영어로 - make use of와 take advantage of", "link": "https://speckofdust.tistory.com/210"});
    blog.posts.push({"id": "post_206", "title": "'이란인, 이란어' 영어로 - Iranian, Persian, Farsi의 구별", "link": "https://speckofdust.tistory.com/206"});
    blog.posts.push({"id": "post_208", "title": "'(돈을, 빚을) 갚다' 영어로 - pay back과 pay off", "link": "https://speckofdust.tistory.com/208"});
    blog.posts.push({"id": "post_207", "title": "은행업무와 관련된 여러 표현들(계좌, 통장, 입금, 수수료, 환전, 이자, 대출, 재테크..) 영어로는?", "link": "https://speckofdust.tistory.com/207"});
    blog.posts.push({"id": "post_209", "title": "'일회용 / 다회용(재사용, 재활용)' 영어로 - disposable(또는 single-use)와 reusable", "link": "https://speckofdust.tistory.com/209"});
    blog.posts.push({"id": "post_205", "title": "'구독하다' 영어로 - subscribe(+ 꼭 알아야할 점)", "link": "https://speckofdust.tistory.com/205"});
    blog.posts.push({"id": "post_202", "title": "'차례대로/순서대로' 영어로 - in turn과 in order의 차이 (+그리고 그 활용법)", "link": "https://speckofdust.tistory.com/202"});
    blog.posts.push({"id": "post_203", "title": "'~치고는' - 영어로 표현하기", "link": "https://speckofdust.tistory.com/203"});
    blog.posts.push({"id": "post_204", "title": "'동갑, 또래' - 영어로 표현하기", "link": "https://speckofdust.tistory.com/204"});
    blog.posts.push({"id": "post_200", "title": "'엿듣다', '도청하다' - 영어로 표현하기", "link": "https://speckofdust.tistory.com/200"});
    blog.posts.push({"id": "post_198", "title": "영화의 배역 관련 용어(등장인물, 주연, 조연, 단역, 엑스트라, 카메오(특별출연, 우정출연) - 영어로 표현하기", "link": "https://speckofdust.tistory.com/198"});
    blog.posts.push({"id": "post_201", "title": "여러 문장부호들 (마침표, 쉼표, 물음표, 느낌표 등등..) - 영어로 표현하기", "link": "https://speckofdust.tistory.com/201"});
    blog.posts.push({"id": "post_199", "title": "영화의 제작 관련 용어(제작(기획), 각본(대본), 연출, 배급, 상영) - 영어로 표현하기(cf. 시사회, 개봉)", "link": "https://speckofdust.tistory.com/199"});
    blog.posts.push({"id": "post_196", "title": "'곧(바로)/잠시 후/이따가/나중에' - 영어로 표현하기", "link": "https://speckofdust.tistory.com/196"});
    blog.posts.push({"id": "post_195", "title": "접미사 'ward'에 대한 글 (upward, forward, inward 등등)", "link": "https://speckofdust.tistory.com/195"});
    blog.posts.push({"id": "post_197", "title": "(월드컵) 토너먼트 관련 용어 영어로 - 32강, 16강, 8강, 4강, 결승 (cf. 예선, 본선)", "link": "https://speckofdust.tistory.com/197"});
    blog.posts.push({"id": "post_194", "title": "인간의 감각(오감) -시각, 후각, 청각, 미각, 촉각 - 영어로", "link": "https://speckofdust.tistory.com/194"});
    blog.posts.push({"id": "post_191", "title": "'혈관(핏줄)'(동맥, 정맥, 모세혈관(실핏줄) 등등..) - 영어로 표현하기", "link": "https://speckofdust.tistory.com/191"});
    blog.posts.push({"id": "post_190", "title": "'모두/전부'를 뜻하는 영어 - 'all'와 'every'의 차이 (cf. each)", "link": "https://speckofdust.tistory.com/190"});
    blog.posts.push({"id": "post_193", "title": "'사춘기' 영어로 - adolescence와 puberty의 차이", "link": "https://speckofdust.tistory.com/193"});
    blog.posts.push({"id": "post_192", "title": "'무시하다' 영어로 - ignore/disregard, dismiss, overlook, look down on", "link": "https://speckofdust.tistory.com/192"});
    blog.posts.push({"id": "post_186", "title": "수영의 각 영법 영어로 - 자유형, 배영, 평영, 접영", "link": "https://speckofdust.tistory.com/186"});
    blog.posts.push({"id": "post_187", "title": "'합치다' 영어로 - combine, unite, add, merge, put together", "link": "https://speckofdust.tistory.com/187"});
    blog.posts.push({"id": "post_188", "title": "'믿다, 신뢰하다' 영어로 - believe와 trust의 구별", "link": "https://speckofdust.tistory.com/188"});
    blog.posts.push({"id": "post_189", "title": "'정확한' 영어로 - exact, accurate, precise의 구별", "link": "https://speckofdust.tistory.com/189"});
    blog.posts.push({"id": "post_183", "title": "사칙연산(가감승제, 덧셈/뺄셈/곱셈/나눗셈) 영어로 표현하기", "link": "https://speckofdust.tistory.com/183"});
    blog.posts.push({"id": "post_184", "title": "'눕다/엎드리다' 영어로 - lie (down), lie on one's stomach/belly/front", "link": "https://speckofdust.tistory.com/184"});
    blog.posts.push({"id": "post_182", "title": "사람의 여러 체형(마른, 날씬한, 통통한, 뚱뚱한 등등...) - 영어로", "link": "https://speckofdust.tistory.com/182"});
    blog.posts.push({"id": "post_185", "title": "'피(혈액)'과 관련된 영어 표현 -코피, 혈액형, 헌혈, 수혈, 백혈구, 적혈구", "link": "https://speckofdust.tistory.com/185"});
    blog.posts.push({"id": "post_181", "title": "바람, 비, 눈, 우박 등등... 기상 현상들 영어로 표현하기", "link": "https://speckofdust.tistory.com/181"});
    blog.posts.push({"id": "post_180", "title": "'공감하다' 영어로 - sympathize with, empathize with, relate to", "link": "https://speckofdust.tistory.com/180"});
    blog.posts.push({"id": "post_179", "title": "수십, 수백, 수천, 수만, 수십만 등등... - 영어로는?", "link": "https://speckofdust.tistory.com/179"});
    blog.posts.push({"id": "post_178", "title": "'일/십/백/천/만/억/조/경....' - 영어로 숫자 단위 읽기", "link": "https://speckofdust.tistory.com/178"});
    blog.posts.push({"id": "post_177", "title": "달의 위상(보름달, 반달, 초승달, 그믐달 등등) - 영어로는?", "link": "https://speckofdust.tistory.com/177"});
    blog.posts.push({"id": "post_176", "title": "'결과'를 뜻하는 단어 중 result와 outcome의 차이", "link": "https://speckofdust.tistory.com/176"});
    blog.posts.push({"id": "post_175", "title": "'조심하다' 영어로 - be careful of와 be careful with의 차이", "link": "https://speckofdust.tistory.com/175"});
    blog.posts.push({"id": "post_174", "title": "'무릎' 영어로 - knee와 lap의 구별", "link": "https://speckofdust.tistory.com/174"});
    blog.posts.push({"id": "post_171", "title": "각 군종을 영어로 표현하기(육/해/공군, 해병대, 예비군) (cf. 민방위)", "link": "https://speckofdust.tistory.com/171"});
    blog.posts.push({"id": "post_173", "title": "'배, 복부' 영어로 - stomach, belly, tummy (cf. abdomen)", "link": "https://speckofdust.tistory.com/173"});
    blog.posts.push({"id": "post_170", "title": "곡물 종류 영어로 - 쌀, 보리, 옥수수, 귀리 등등...", "link": "https://speckofdust.tistory.com/170"});
    blog.posts.push({"id": "post_172", "title": "GI 지수의 뜻은? ('GI'는 무엇의 약자?)", "link": "https://speckofdust.tistory.com/172"});
    blog.posts.push({"id": "post_167", "title": "'전부/전체/모두'를 뜻하는 단어 中 'whole'과 'entire'의 차이", "link": "https://speckofdust.tistory.com/167"});
    blog.posts.push({"id": "post_166", "title": "'설거지' 관련 표현 영어로 - dish-washing, washing-up 등등(cf. 관련 표현들)", "link": "https://speckofdust.tistory.com/166"});
    blog.posts.push({"id": "post_169", "title": "'유전의, 유전되는' 영어로 - hereditary와 genetic의 차이 (cf. congenital은?)", "link": "https://speckofdust.tistory.com/169"});
    blog.posts.push({"id": "post_168", "title": "망원경/현미경/내시경 등등 영어로 - telescope/microscope/endoscope... (+scope의 의미)", "link": "https://speckofdust.tistory.com/168"});
    blog.posts.push({"id": "post_162", "title": "날카로운, 뾰족한 영어로 -  sharp, pointed/pointy", "link": "https://speckofdust.tistory.com/162"});
    blog.posts.push({"id": "post_164", "title": "'티 나다, 티 내다' 영어로 - 'show'", "link": "https://speckofdust.tistory.com/164"});
    blog.posts.push({"id": "post_163", "title": "'일어나다/깨다/깨우다' 영어로 - get up과 wake up의 구별", "link": "https://speckofdust.tistory.com/163"});
    blog.posts.push({"id": "post_165", "title": "'방해하다, 끼어들다, 간섭하다' 영어로 - disturb/interrupt/interfere (cf. be(get) in the way)", "link": "https://speckofdust.tistory.com/165"});
    blog.posts.push({"id": "post_160", "title": "'죽음'에 관한 영어 표현 - deadly, lethal, fatal, mortal의 구별", "link": "https://speckofdust.tistory.com/160"});
    blog.posts.push({"id": "post_161", "title": "'놀라운, 충격적인' 영어로 - surprised와 shocked의 구별", "link": "https://speckofdust.tistory.com/161"});
    blog.posts.push({"id": "post_159", "title": "'내 친구' 영어로 - 'my friend'와 'a friend of mine'의 차이", "link": "https://speckofdust.tistory.com/159"});
    blog.posts.push({"id": "post_158", "title": "'차별하다' 영어로 - discriminate (cf. 많이 틀리는 중요한 부분)", "link": "https://speckofdust.tistory.com/158"});
    blog.posts.push({"id": "post_156", "title": "초식 동물, 육식 동물, 잡식 동물 영어로 - herbivore, carnivore, omnivore", "link": "https://speckofdust.tistory.com/156"});
    blog.posts.push({"id": "post_157", "title": "작사/작곡/편곡 영어로 (+작사가, 작곡가, 편곡가는 영어로?)", "link": "https://speckofdust.tistory.com/157"});
    blog.posts.push({"id": "post_154", "title": "'주행성', '야행성' 영어로 - diurnal, nocturnal", "link": "https://speckofdust.tistory.com/154"});
    blog.posts.push({"id": "post_155", "title": "'일부러, 고의로, 의도적으로' 영어로 - on purpose, deliberately, intentionally", "link": "https://speckofdust.tistory.com/155"});
    blog.posts.push({"id": "post_150", "title": "'분수'에 관한 영어 표현(분모, 분자, 가분수)", "link": "https://speckofdust.tistory.com/150"});
    blog.posts.push({"id": "post_151", "title": "'분수'를 영어로 읽는 여러 방법", "link": "https://speckofdust.tistory.com/151"});
    blog.posts.push({"id": "post_153", "title": "박(박자), 음표, 쉼표,영어로 - beat(time, meter), note, rest,", "link": "https://speckofdust.tistory.com/153"});
    blog.posts.push({"id": "post_152", "title": "'자랑하다' 영어로 - brag, boast, show off", "link": "https://speckofdust.tistory.com/152"});
    blog.posts.push({"id": "post_146", "title": "percentage - 퍼센테이지(x) 퍼센티지(o) (cf. '프로'는?)", "link": "https://speckofdust.tistory.com/146"});
    blog.posts.push({"id": "post_148", "title": "시험에 합격하다/떨어지다 영어로 - pass와 fail", "link": "https://speckofdust.tistory.com/148"});
    blog.posts.push({"id": "post_147", "title": "떠오르다/떠올리다 영어로 - think of, come up with, remind, come to mind, ring a bell, occur to", "link": "https://speckofdust.tistory.com/147"});
    blog.posts.push({"id": "post_149", "title": "'냄새, 향기, 악취' 관련 표현 영어로  - smell, odor, scent, aroma, fragrance, stench, stink", "link": "https://speckofdust.tistory.com/149"});
    blog.posts.push({"id": "post_142", "title": "'~와 다른' 영어로 - different from/to/than의 차이는?", "link": "https://speckofdust.tistory.com/142"});
    blog.posts.push({"id": "post_143", "title": "'~와 같은' 영어로 - same as/equal to/identical to", "link": "https://speckofdust.tistory.com/143"});
    blog.posts.push({"id": "post_144", "title": "싱어송라이터 - sing-a-song-writer(x), singer-songwriter(o)", "link": "https://speckofdust.tistory.com/144"});
    blog.posts.push({"id": "post_145", "title": "로맨티스트(romantist)? (로맨티시스트)romanticist? / 나르시스트(narcist)? 나르시시스트(narcissist)?", "link": "https://speckofdust.tistory.com/145"});
    blog.posts.push({"id": "post_139", "title": "'늦잠 자다' 영어로 - oversleep과 sleep in의 차이점", "link": "https://speckofdust.tistory.com/139"});
    blog.posts.push({"id": "post_140", "title": "'알려주다' 영어로 - inform/notify/reveal/disclose/divulge (cf. let know)", "link": "https://speckofdust.tistory.com/140"});
    blog.posts.push({"id": "post_141", "title": "'자외선'과 '적외선' 영어로 - 'ultraviolet'과 'infrared' (cf. 선크림은 영어로?)", "link": "https://speckofdust.tistory.com/141"});
    blog.posts.push({"id": "post_138", "title": "'다람쥐' 영어로 - 'squirrel'과 'chipmunk'의 구별", "link": "https://speckofdust.tistory.com/138"});
    blog.posts.push({"id": "post_136", "title": "'거꾸로, 반대로' 영어로 -opposite, the other way around, 그 외 표현들", "link": "https://speckofdust.tistory.com/136"});
    blog.posts.push({"id": "post_137", "title": "'새우' 영어로 - shrimp와 prawn의 구별", "link": "https://speckofdust.tistory.com/137"});
    blog.posts.push({"id": "post_134", "title": "선순환, 악순환 영어로 - virtuous/vicious cycle(circle)", "link": "https://speckofdust.tistory.com/134"});
    blog.posts.push({"id": "post_135", "title": "'가만히' 영어로 - 'still'", "link": "https://speckofdust.tistory.com/135"});
    blog.posts.push({"id": "post_132", "title": "'빠른' 영어로 - fast, quick, rapid의 차이점", "link": "https://speckofdust.tistory.com/132"});
    blog.posts.push({"id": "post_133", "title": "'미리' 영어로 - in advance / beforehand / ahead of time", "link": "https://speckofdust.tistory.com/133"});
    blog.posts.push({"id": "post_130", "title": "북극, 남극 영어로 - 'arctic'과 'antarctic' (cf. north/south pole)", "link": "https://speckofdust.tistory.com/130"});
    blog.posts.push({"id": "post_131", "title": "'혈압' 관련 표현 영어로 -고혈압/저혈압 (cf. mmhg, sys/dia는 무슨 뜻?)", "link": "https://speckofdust.tistory.com/131"});
    blog.posts.push({"id": "post_126", "title": "person(사람)의 복수형 - people? persons?", "link": "https://speckofdust.tistory.com/126"});
    blog.posts.push({"id": "post_127", "title": "'정말로, 진짜로' 영어로 - really와 seriously의 차이", "link": "https://speckofdust.tistory.com/127"});
    blog.posts.push({"id": "post_128", "title": "'적도', '위도', '경도' 영어로 -  equator / latitude /  longitude (cf. 본초 자오선)", "link": "https://speckofdust.tistory.com/128"});
    blog.posts.push({"id": "post_129", "title": "북반구, 남반구 영어로 - northern/southern hemisphere", "link": "https://speckofdust.tistory.com/129"});
    blog.posts.push({"id": "post_122", "title": "'운명' 영어로 - destiny, fate, doom의 차이점", "link": "https://speckofdust.tistory.com/122"});
    blog.posts.push({"id": "post_123", "title": "'넣다', '꺼내다/빼다' 영어로 - put in과 take out", "link": "https://speckofdust.tistory.com/123"});
    blog.posts.push({"id": "post_125", "title": "'넘어지다, 넘어뜨리다' 영어로 (cf. 희한하게도 이 표현이 어려운 이유)", "link": "https://speckofdust.tistory.com/125"});
    blog.posts.push({"id": "post_124", "title": "'옷을 입다/벗다' 영어로 (cf. put on과 wear의 차이점)", "link": "https://speckofdust.tistory.com/124"});
    blog.posts.push({"id": "post_119", "title": "'평균, 중앙값' 영어로 - average, mean, median의 차이점", "link": "https://speckofdust.tistory.com/119"});
    blog.posts.push({"id": "post_120", "title": "비슷한 단어 -  terrible/terrify/terrific과  horrible/horrify/horrific", "link": "https://speckofdust.tistory.com/120"});
    blog.posts.push({"id": "post_121", "title": "투명, 반투명, 불투명 영어로 - transparent, translucent, opaque", "link": "https://speckofdust.tistory.com/121"});
    blog.posts.push({"id": "post_118", "title": "'(표, 칸, 설문 등을) 작성하다/채우다' 영어로 - fill in과 fill out 차이", "link": "https://speckofdust.tistory.com/118"});
    blog.posts.push({"id": "post_115", "title": "헷갈리는 두 단어 - 'gratitude'와 'gratification'의 차이", "link": "https://speckofdust.tistory.com/115"});
    blog.posts.push({"id": "post_117", "title": "'데우다'와 '식히다' - 영어로는?", "link": "https://speckofdust.tistory.com/117"});
    blog.posts.push({"id": "post_116", "title": "'불을 붙이다, 불을 끄다' 영어로", "link": "https://speckofdust.tistory.com/116"});
    blog.posts.push({"id": "post_114", "title": "'감사하다' 영어로 - thank와 appreciate의 차이", "link": "https://speckofdust.tistory.com/114"});
    blog.posts.push({"id": "post_110", "title": "'복수, 복수하다' 영어로 - 'revenge'와 'avenge'의 차이점", "link": "https://speckofdust.tistory.com/110"});
    blog.posts.push({"id": "post_112", "title": "'말더듬' 영어로 - 'stutter'와 'stammer'의 차이 (번외: stumble)", "link": "https://speckofdust.tistory.com/112"});
    blog.posts.push({"id": "post_113", "title": "'중얼거리다' 영어로 -  'murmur', 'mutter', 'mumble'", "link": "https://speckofdust.tistory.com/113"});
    blog.posts.push({"id": "post_111", "title": "이상,이하 / 초과, 미만 - 영어로는?", "link": "https://speckofdust.tistory.com/111"});
    blog.posts.push({"id": "post_108", "title": "'판매 중'과 '할인 중' 영어로? - 'for sale'과 'on sale'의 차이", "link": "https://speckofdust.tistory.com/108"});
    blog.posts.push({"id": "post_107", "title": "'잘하다, 잘못하다' - 영어로는?", "link": "https://speckofdust.tistory.com/107"});
    blog.posts.push({"id": "post_109", "title": "'바람이 불다', '풍선을 불다', '촛불을 불다' 영어로? - 'blow'와 그 외 관련 표현", "link": "https://speckofdust.tistory.com/109"});
    blog.posts.push({"id": "post_106", "title": "'맞히다',  '틀리다' - 영어로는?", "link": "https://speckofdust.tistory.com/106"});
    blog.posts.push({"id": "post_104", "title": "'부끄럽다' 영어로 - shy? ashamed?", "link": "https://speckofdust.tistory.com/104"});
    blog.posts.push({"id": "post_105", "title": "'부러운, 질투 나는' 영어로 - envious와 jealous의 차이", "link": "https://speckofdust.tistory.com/105"});
    blog.posts.push({"id": "post_102", "title": "'지난, 이전의' 영어로 - previous, former, ex 차이점", "link": "https://speckofdust.tistory.com/102"});
    blog.posts.push({"id": "post_103", "title": "'일대일로' 영어로 - 'one-on-one'과 'one-to-one'의 차이점", "link": "https://speckofdust.tistory.com/103"});
    blog.posts.push({"id": "post_98", "title": "popular와 famous의 차이점", "link": "https://speckofdust.tistory.com/98"});
    blog.posts.push({"id": "post_100", "title": "'피할 수 없는' 영어로 - unavoidable? inevitable?", "link": "https://speckofdust.tistory.com/100"});
    blog.posts.push({"id": "post_96", "title": "'지금까지' 영어로 - 'until now'와 'so far'의 차이", "link": "https://speckofdust.tistory.com/96"});
    blog.posts.push({"id": "post_99", "title": "'인정하다' 영어로 - admit과  acknowledge의 차이점", "link": "https://speckofdust.tistory.com/99"});
    blog.posts.push({"id": "post_94", "title": "'축하하다' 영어로 - congratulate? celebrate?", "link": "https://speckofdust.tistory.com/94"});
    blog.posts.push({"id": "post_95", "title": "'기밀 등급 분류' 영어로 (cf. confidential과 classified의 차이는?)", "link": "https://speckofdust.tistory.com/95"});
    blog.posts.push({"id": "post_93", "title": "'가려운' 영어로 -  itchy? scratchy?", "link": "https://speckofdust.tistory.com/93"});
    blog.posts.push({"id": "post_92", "title": "'Rule of thumb' - 이 표현의 해석이 까다로운 이유", "link": "https://speckofdust.tistory.com/92"});
    blog.posts.push({"id": "post_88", "title": "'결혼' 관련 표현 영어로 - marry/marriage/wedding 등...", "link": "https://speckofdust.tistory.com/88"});
    blog.posts.push({"id": "post_91", "title": "'전염병, 풍토병' 영어로 - endemic, epidemic, pandemic 차이는?", "link": "https://speckofdust.tistory.com/91"});
    blog.posts.push({"id": "post_89", "title": "24절기 中 '하지, 동지 / 춘분, 추분' 영어로", "link": "https://speckofdust.tistory.com/89"});
    blog.posts.push({"id": "post_90", "title": "'털, 수염, 구레나룻' 영어로 (hair / fur / beard, mustache, sideburns)", "link": "https://speckofdust.tistory.com/90"});
    blog.posts.push({"id": "post_85", "title": "'졸업(식), 졸업하다' 영어로 - graduation / graduate (+ 주의할 점)", "link": "https://speckofdust.tistory.com/85"});
    blog.posts.push({"id": "post_84", "title": "'맨 처음부터/맨땅에 헤딩으로' 영어로- 'from scratch'", "link": "https://speckofdust.tistory.com/84"});
    blog.posts.push({"id": "post_87", "title": "'확률, 가능성' 영어로 - probability와  possibility 차이", "link": "https://speckofdust.tistory.com/87"});
    blog.posts.push({"id": "post_86", "title": "많이들 헷갈려 하는 'choose'와 'choose from'의 차이", "link": "https://speckofdust.tistory.com/86"});
    blog.posts.push({"id": "post_82", "title": "'구분하다/구별하다' 영어로 - 'distinguish'", "link": "https://speckofdust.tistory.com/82"});
    blog.posts.push({"id": "post_83", "title": "'부동산' 영어로 - real estate / real property.  근데 왜?", "link": "https://speckofdust.tistory.com/83"});
    blog.posts.push({"id": "post_81", "title": "'능력' 영어로  -  ability / capability / capacity 차이점", "link": "https://speckofdust.tistory.com/81"});
    blog.posts.push({"id": "post_80", "title": "'대기권(대류권/성층권/중간권/열권)' 영어로.  그리고 각각의 어원은?", "link": "https://speckofdust.tistory.com/80"});
    blog.posts.push({"id": "post_76", "title": "'맛' 표현 (달콤한, 짠, 싱거운, 매운, 신, 쓴)  -  영어로 (기초)", "link": "https://speckofdust.tistory.com/76"});
    blog.posts.push({"id": "post_79", "title": "'싸인' 영어로  -  Sign? Signature? Autograph?", "link": "https://speckofdust.tistory.com/79"});
    blog.posts.push({"id": "post_77", "title": "'포도당' 영어로 - Glucose? Dextrose?  Grape sugar?", "link": "https://speckofdust.tistory.com/77"});
    blog.posts.push({"id": "post_78", "title": "'참다, 견디다' 영어로 -  tolerate/ stand  / bear / put up with / take / hold", "link": "https://speckofdust.tistory.com/78"});
    blog.posts.push({"id": "post_73", "title": "'가정하다, 추정하다' 영어로 - assume, suppose, presume 차이?", "link": "https://speckofdust.tistory.com/73"});
    blog.posts.push({"id": "post_75", "title": "'연장하다/확장하다, 늘리다' 영어로 - extend와 expand의 차이", "link": "https://speckofdust.tistory.com/75"});
    blog.posts.push({"id": "post_74", "title": "'코드' 영어로 - code / cord / chord 차이", "link": "https://speckofdust.tistory.com/74"});
    blog.posts.push({"id": "post_72", "title": "'멸종하다' 영어로 - 'become/go extinct'와 'die out' (cf. '멸종위기' 영어로)", "link": "https://speckofdust.tistory.com/72"});
    blog.posts.push({"id": "post_70", "title": "'줄다리기' 영어로 - 'tug of war'.  그 유래는?", "link": "https://speckofdust.tistory.com/70"});
    blog.posts.push({"id": "post_69", "title": "'착각하다/헷갈리다/혼동하다' 영어로 - mistake/confuse/mix up", "link": "https://speckofdust.tistory.com/69"});
    blog.posts.push({"id": "post_71", "title": "성,이름 영어로 -(first name, last name, surname, family name, given name 뜻)", "link": "https://speckofdust.tistory.com/71"});
    blog.posts.push({"id": "post_68", "title": "(얼굴에 나는 것들) 점/여드름/기미/주근깨 - 영어로? (+ 모공, 딱지는 영어로?)", "link": "https://speckofdust.tistory.com/68"});
    blog.posts.push({"id": "post_65", "title": "'약어/약자' 영어로? -  abbreviation / initial / acronym 차이는?", "link": "https://speckofdust.tistory.com/65"});
    blog.posts.push({"id": "post_64", "title": "known as, known by, known for, known to -각각의 뜻과 그 차이는?", "link": "https://speckofdust.tistory.com/64"});
    blog.posts.push({"id": "post_66", "title": "'자막' 영어로 -  Subtitle? CC? (여기서 CC는 무엇의 줄임말?)", "link": "https://speckofdust.tistory.com/66"});
    blog.posts.push({"id": "post_67", "title": "'박수' - 영어로?   (clap / applause / ovation)", "link": "https://speckofdust.tistory.com/67"});
    blog.posts.push({"id": "post_63", "title": "'넓이/부피' 표현 단위 中 '제곱미터, 세제곱미터' - 영어로는?", "link": "https://speckofdust.tistory.com/63"});
    blog.posts.push({"id": "post_61", "title": "'자동' 영어로 - automatic? automated?  / 접두사 'auto-'에 관해", "link": "https://speckofdust.tistory.com/61"});
    blog.posts.push({"id": "post_62", "title": "'점' 영어로 -  point/ dot/spot  차이?? (cf. '얼굴에 나는 점'은 영어로?)", "link": "https://speckofdust.tistory.com/62"});
    blog.posts.push({"id": "post_60", "title": "'비율' 영어로 - ratio? proportion?", "link": "https://speckofdust.tistory.com/60"});
    blog.posts.push({"id": "post_56", "title": "도형 中 '삼각형, 사각형, 원' 관련 표현들 - 영어로는?", "link": "https://speckofdust.tistory.com/56"});
    blog.posts.push({"id": "post_58", "title": "'입체도형' (구, 원기둥, 원뿔,  각뿔, 각기둥, 직육면체, 정육면체 / 부피) - 영어로", "link": "https://speckofdust.tistory.com/58"});
    blog.posts.push({"id": "post_57", "title": "'다각형' (삼각형, 사각형, 오각형, 육각형 등등..) - 영어로", "link": "https://speckofdust.tistory.com/57"});
    blog.posts.push({"id": "post_59", "title": "'원' 관련 표현  영어로- 중심, 지름, 반지름, 둘레", "link": "https://speckofdust.tistory.com/59"});
    blog.posts.push({"id": "post_53", "title": "동물 분류 中 '포유류, 영장류, 파충류, 양서류, 갑각류' - 영어로, 그리고 그 어원", "link": "https://speckofdust.tistory.com/53"});
    blog.posts.push({"id": "post_51", "title": "'질량(무게)' 단위 영어 표현 - 온스(ounce), 파운드(pound)", "link": "https://speckofdust.tistory.com/51"});
    blog.posts.push({"id": "post_52", "title": "'많은'을 뜻하는 영어 접두사: 'multi-'와 'poly-'의 차이는?", "link": "https://speckofdust.tistory.com/52"});
    blog.posts.push({"id": "post_55", "title": "'도형' 관련 표현들 -점, 선(직선, 곡선, 대각선), 넓이, 각도(직각, 예각, 둔각), 평행, 수직) 등등.. - 영어로는?", "link": "https://speckofdust.tistory.com/55"});
    blog.posts.push({"id": "post_46", "title": "'관절, 연골, 인대, 건' - 각각 영어로 어떻게 표현??", "link": "https://speckofdust.tistory.com/46"});
    blog.posts.push({"id": "post_50", "title": "'부피' 단위 영어 표현 - 온스(ounce), 파인트(pint), 쿼트(quart), 갤런(gallon)", "link": "https://speckofdust.tistory.com/50"});
    blog.posts.push({"id": "post_48", "title": "도량형(측정 단위) - 미터법(metric system) vs 야드파운드법(imperial system)", "link": "https://speckofdust.tistory.com/48"});
    blog.posts.push({"id": "post_49", "title": "'길이, 거리'  단위 영어 표현 - 인치(inch), 피트(feet), 야드(yard), 마일(mile)", "link": "https://speckofdust.tistory.com/49"});
    blog.posts.push({"id": "post_43", "title": "'포기하다' 영어로- 'give up' 과 'give up on'의 차이", "link": "https://speckofdust.tistory.com/43"});
    blog.posts.push({"id": "post_42", "title": "'금고' 영어로 - safe? vault?", "link": "https://speckofdust.tistory.com/42"});
    blog.posts.push({"id": "post_45", "title": "'상쇄하다/균형을 맞추다' 영어로 표현 - balance out, cancel out", "link": "https://speckofdust.tistory.com/45"});
    blog.posts.push({"id": "post_44", "title": "'항복하다/굴복하다' 영어로 - 'give in'", "link": "https://speckofdust.tistory.com/44"});
    blog.posts.push({"id": "post_39", "title": "'인용' 관련 표현 영어로-  quotation, citation, reference", "link": "https://speckofdust.tistory.com/39"});
    blog.posts.push({"id": "post_40", "title": "'take'와 'bring'의 공통점 및 (매우 중요한) 차이점", "link": "https://speckofdust.tistory.com/40"});
    blog.posts.push({"id": "post_38", "title": "'다리'에 관한 표현 영어로(종아리, 무릎, 허벅지 등등..)", "link": "https://speckofdust.tistory.com/38"});
    blog.posts.push({"id": "post_41", "title": "'유산' 영어로 - inheritance? heritage? legacy?", "link": "https://speckofdust.tistory.com/41"});
    blog.posts.push({"id": "post_36", "title": "'발'에 관한 표현 영어로(발가락, 발등, 발바닥 등등..)", "link": "https://speckofdust.tistory.com/36"});
    blog.posts.push({"id": "post_37", "title": "'팔'에 관한 표현 영어로 (팔꿈치, 전완, 상완 등등..)", "link": "https://speckofdust.tistory.com/37"});
    blog.posts.push({"id": "post_33", "title": "'대체하다' 영어로 - replace와 substitute의 차이는?", "link": "https://speckofdust.tistory.com/33"});
    blog.posts.push({"id": "post_34", "title": "'들어와, 들어오세요' 영어로 - come in? come on in?", "link": "https://speckofdust.tistory.com/34"});
    blog.posts.push({"id": "post_32", "title": "'눈썹' 영어로- eyelash? eyebrow??  (번외: '눈꺼풀'은?)", "link": "https://speckofdust.tistory.com/32"});
    blog.posts.push({"id": "post_31", "title": "'위험한' 영어로 -  'dangerous'와 'risky'의 차이는?", "link": "https://speckofdust.tistory.com/31"});
    blog.posts.push({"id": "post_29", "title": "'솔직히'  - 영어로 어떻게 표현할까", "link": "https://speckofdust.tistory.com/29"});
    blog.posts.push({"id": "post_28", "title": "손가락(엄지/검지/중지/약지/소지) , 손등, 손바닥 등등.. 영어로 표현", "link": "https://speckofdust.tistory.com/28"});
    blog.posts.push({"id": "post_26", "title": "'과일과 야채' 영어로 - fruit(s) and vegetable(s) ????", "link": "https://speckofdust.tistory.com/26"});
    blog.posts.push({"id": "post_27", "title": "'우회(迂回)' 영어로 - 'detour'", "link": "https://speckofdust.tistory.com/27"});
    blog.posts.push({"id": "post_24", "title": "'distinct'와 'distinctive'의 차이점", "link": "https://speckofdust.tistory.com/24"});
    blog.posts.push({"id": "post_25", "title": "'더 좋아하다' 영어로 - like better?  like more?", "link": "https://speckofdust.tistory.com/25"});
    blog.posts.push({"id": "post_20", "title": "'한번에' 영어로 - at once(at the same time) / at a time", "link": "https://speckofdust.tistory.com/20"});
    blog.posts.push({"id": "post_22", "title": "'속도를 늦추다 / 높이다' 영어로 - 'slow down', 'speed up'", "link": "https://speckofdust.tistory.com/22"});
    blog.posts.push({"id": "post_23", "title": "'닫힘'은 'closed'인데, '열림'은 왜 'open'?", "link": "https://speckofdust.tistory.com/23"});
    blog.posts.push({"id": "post_19", "title": "'반올림하다' 영어로 - 'round off'", "link": "https://speckofdust.tistory.com/19"});
    blog.posts.push({"id": "post_17", "title": "'기준' 영어로 - standard? criterion?", "link": "https://speckofdust.tistory.com/17"});
    blog.posts.push({"id": "post_16", "title": "'전화를 끊다' 영어로 - 'hang up'", "link": "https://speckofdust.tistory.com/16"});
    blog.posts.push({"id": "post_15", "title": "'전화를 걸다' 영어로 - call, ring, phone 등등..", "link": "https://speckofdust.tistory.com/15"});
    blog.posts.push({"id": "post_18", "title": "'소수' 영어로 - 'decimal'", "link": "https://speckofdust.tistory.com/18"});
    blog.posts.push({"id": "post_11", "title": "in case~ / in case of~ / in the case of~ 차이점", "link": "https://speckofdust.tistory.com/11"});
    blog.posts.push({"id": "post_14", "title": "'전화 받다' 영어로 - pick up the phone / answer a call 등등... (2)", "link": "https://speckofdust.tistory.com/14"});
    blog.posts.push({"id": "post_12", "title": "'재촉하다' 영어로 - rush / hurry (up)", "link": "https://speckofdust.tistory.com/12"});
    blog.posts.push({"id": "post_13", "title": "'전화 받다' 영어로 - pick up the phone / answer a call 등등... (1)", "link": "https://speckofdust.tistory.com/13"});
    blog.posts.push({"id": "post_10", "title": "'paraphrase'라는 영어 표현 - '다른 말로 바꾸어 표현하다/표현한 것'", "link": "https://speckofdust.tistory.com/10"});
    blog.posts.push({"id": "post_9", "title": "'소리내어~' 영어로 - out loud / aloud", "link": "https://speckofdust.tistory.com/9"});
    blog.posts.push({"id": "post_7", "title": "search와 search 'for'의 차이", "link": "https://speckofdust.tistory.com/7"});
    blog.posts.push({"id": "post_8", "title": "'찾다' 영어로 -  'look for'와 'find'의 차이점", "link": "https://speckofdust.tistory.com/8"});
    blog.posts.push({"id": "post_5", "title": "'이르다' 영어로= 'tell on'", "link": "https://speckofdust.tistory.com/5"});
    blog.posts.push({"id": "post_6", "title": "'혼내다' 영어로 - tell off", "link": "https://speckofdust.tistory.com/6"});
    window.blogsData.push(blog);
})();